### ISSUE TITLE
About the MegDL Frame.

### ISSUE THREAD

**Issue by Yuchen-ge** [caiyuanhao1998/RSN#12]
Excuse me. Where can i find the code of MegDL?

**Comment by megvii-wzc** [comment]
MegDL is an inner DL framework of Megvii. Now we have the open source version of MegDL: MegEngine(https://github.com/MegEngine/MegEngine),  the code of RSN in MegEngine will come soon. Thanks!

**Comment by IAm20cm** [comment]
不用等了，作者盗号给他自己刷星星！他就是个骗子！🤥
@megvii-wzc @Yuchen-ge
