### ISSUE TITLE
where is the PRM code in your RSN project

### ISSUE THREAD

**Issue by superWSL** [caiyuanhao1998/RSN#17]
Hello, where is the PRM code in your RSN project, i can not find that, is the code not published?

**Comment by Tiago-Roxo** [comment]
Hi! I am not one of the authors but I think you can find the PRM code in exps/4XRSN18.coco/network.py: https://github.com/caiyuanhao1998/RSN/blob/master/exps/4XRSN18.coco/network.py. In line 337, there is a class name 'PRM'. I am not sure if it is used anywhere in the network, though.

**Comment by caiyuanhao1998** [comment]
In Lines 337-371, https://github.com/caiyuanhao1998/RSN/blob/master/exps/4XRSN18.coco/network.py

Try to use it at the output end :)
