### ISSUE TITLE
about coco 2017

### ISSUE THREAD

**Issue by WeianMao** [caiyuanhao1998/RSN#19]
the training set here is called 'train_val_minus_minival_2014.json'. But the paper reports the result on COCO2017. How can I train it on COCO2017? Thank you!

**Comment by caiyuanhao1998** [comment]
Hi, please use the MMPose [codebase](https://github.com/open-mmlab/mmpose) with their [pre-trained model zoo](https://mmpose.readthedocs.io/en/latest/model_zoo_papers/backbones.html#rsn-eccv-2020) for COCO-2017
