### ISSUE TITLE
运行RSN18.mpii出错

### ISSUE THREAD

**Issue by YuQi9797** [caiyuanhao1998/RSN#20]
作者您好，我再运行程序时，使用命令
`python -m torch.distributed.launch --nproc_per_node=1 train.py`

但是错误告诉我：
AttributeError: 'Engine' object has no attribute 'local_rank'.

请问是我分布式这里出错了吗？  该如何处理呢？

**Comment by YuQi9797** [comment]
https://github.com/caiyuanhao1998/RSN/blob/master/cvpack/torch_modeling/engine/engine.py#L55-L66

当我self.distributed 未False时，似乎self.local_rank并没有定义。

**Comment by KAWAKO-in-GAYHUB** [comment]
![image](https://user-images.githubusercontent.com/54660064/202602331-44ff83ad-5372-4e56-8ee6-1489f8c7fe64.png)
强行在train.py里把它屏蔽掉

**Comment by caiyuanhao1998** [comment]
嗯嗯，直接单机训练也是可以的
