### ISSUE TITLE
Could  you submit the 4xRSN-50 code?

### ISSUE THREAD

**Issue by imay99** [caiyuanhao1998/RSN#21]
Could  you submit the 4xRSN-50 code?

**Comment by IAm20cm** [comment]
不用等了，作者盗号给他自己刷星星！他就是个骗子！🤥

**Comment by caiyuanhao1998** [comment]
RSN-50 is easy, just modify the numbers of the blocks in
https://github.com/caiyuanhao1998/RSN/blob/master/exps/4XRSN18.coco/network.py#L324
from [2, 2, 2, 2] to [3, 4, 6, 3] and then modify the stage number to 4
