### ISSUE TITLE
where is the retrained model?

### ISSUE THREAD

**Issue by liuzhenhui** [caiyuanhao1998/RSN#25]
I train RSN on COCO2017 dataset . i cant get a best performance .i dont know the reason ,so i want get a retrained model ,thanks

**Comment by lofyol** [comment]
up up

**Comment by IAm20cm** [comment]
不用等了，作者盗号给他自己刷星星！他就是个骗子！🤥
@lofyol @liuzhenhui

**Comment by awekling** [comment]
Hey Loser! Why Did You Rape/Abuse My Account for Your Damnit Project?

**Comment by Hyrtsi** [comment]
Hi, it would be nice to get a pre-trained model to test this. Thank you.

**Comment by caiyuanhao1998** [comment]
Hi, here are the pre-trained model zoo:
https://mmpose.readthedocs.io/en/latest/model_zoo_papers/backbones.html#rsn-eccv-2020
