### ISSUE TITLE
作者能给个训练好的模型吗

### ISSUE THREAD

**Issue by lofyol** [caiyuanhao1998/RSN#26]

**Comment by Crescentz** [comment]
能给一个吗

**Comment by IAm20cm** [comment]
不用等了，作者盗号给他自己刷星星！他就是个骗子！🤥

**Comment by IAm20cm** [comment]
> 能给一个吗

@Crescentz 不用等了，作者盗号给他自己刷星星！他就是个骗子！🤥

**Comment by awekling** [comment]
Hey Loser! Why Did You Rape/Abuse My Account for Your Damnit Project?

**Comment by caiyuanhao1998** [comment]
https://mmpose.readthedocs.io/en/latest/model_zoo_papers/backbones.html#rsn-eccv-2020
