### ISSUE TITLE
参数问题?

### ISSUE THREAD

**Issue by JACKYLUO1991** [caiyuanhao1998/RSN#3]
TRAIN.NUM_KEYPOINTS_HALF_BODY 您好，请问一下这个参数根据什么设定的呢？期待您的回复...

**Comment by megvii-wzc** [comment]
English please. This param is set by experimental experiments.

**Comment by caiyuanhao1998** [comment]
Which script do you find this parameter in?

**Comment by JACKYLUO1991** [comment]
@caiyuanhao1998 In attribute.py, and use different parameters for mpii and coco dataset. I am confused about how to set this parameter

**Comment by caiyuanhao1998** [comment]
This parameter is the threshold for body augmentation, please refer to JointsDataset.py line 106.

**Comment by JACKYLUO1991** [comment]
@caiyuanhao1998  Thanks，Can you provide ‘half body transform’ reference paper?

**Comment by caiyuanhao1998** [comment]
emmmm.....I'm not sure , it's a common data augmentation for human pose estmation
