### ISSUE TITLE
Multi-person output

### ISSUE THREAD

**Issue by shaharl6000** [caiyuanhao1998/RSN#30]
I don't understand how to calculate multi person keypoints output, I ran RSN18, and the output is 17x64x48, hence one keypoints "heatmap" on the original image, how do I outputs few people's keypoints predictions?

**Comment by caiyuanhao1998** [comment]
RSN is a top-down method. The pipeline is

(i) use a human detector to locate the positions of human instances

(ii) use RSN to perform single-person pose estimation for each detected human instance
