### ISSUE TITLE
How to ensemble the models?

### ISSUE THREAD

**Issue by tang576225574** [caiyuanhao1998/RSN#31]
We noticed that a best result was gained by an ensembled model in the paper (e.g. table 6). However, few details were mentioned about it, could you give some explanations about how to reproduce this ensemble result?

**Comment by caiyuanhao1998** [comment]
There are two ensemble strategies:

Self-ensemble: rotate, flip the input and infer them to obtain the outputs. Re-transform the outputs and average them.

Multi-model ensemble: average the output heatmaps of different models.
