### ISSUE TITLE
Cain I train my custom dataset? - keypoint num = 8

### ISSUE THREAD

**Issue by hi-one-gg** [caiyuanhao1998/RSN#32]
I have a custom dataset.
It has only 8 keypoints, not 17 like COCO.

Is there any method to train my custom dataset? 

Congratulations on winning first place in the COCO🎉!

**Comment by caiyuanhao1998** [comment]
Hi, Just adjust the channels of output heap maps to 8

**Comment by hi-one-gg** [comment]
@caiyuanhao1998  Thanks, I'll try it.
