### ISSUE TITLE
Why do you use center information in ground truth for post processing? 

### ISSUE THREAD

**Issue by mrtranducdung** [caiyuanhao1998/RSN#33]
I saw this line in the get_results function
kps[:, 0] = kps[:, 0] / cfg.INPUT_SHAPE[1] * scales[i][0] + \
            centers[i][0] - scales[i][0] * 0.5
kps[:, 1] = kps[:, 1] / cfg.INPUT_SHAPE[0] * scales[i][1] + \
             centers[i][1] - scales[i][1] * 0.5
If you use the information in ground truth and get a high score, it is unfair. Could you please explain if I misunderstand?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

This is the post-processing in [MSPN](https://github.com/megvii-research/MSPN), I just follow this setting for fair comparison.
