### ISSUE TITLE
Can the RSN model detect multiple human in an image?

### ISSUE THREAD

**Issue by Zannnn** [caiyuanhao1998/RSN#34]
https://github.com/caiyuanhao1998/RSN/issues/1
The code you provided here can only draw one human body. How can I draw multiple human bodies in the image? Can the RSN model detect multiple human keypoints in an image?

**Comment by Zannnn** [comment]
ok I found the answer here https://github.com/caiyuanhao1998/RSN/issues/30.

**Comment by caiyuanhao1998** [comment]
OK. Thanks for your interest.
