### ISSUE TITLE
About the PRM module

### ISSUE THREAD

**Issue by murdockhou** [caiyuanhao1998/RSN#4]
Hi, thanks for your work first. I get some confused about PRM module your paper write. 

In [here](https://github.com/caiyuanhao1998/RSN/blob/master/exps/4XRSN18.coco/network.py#L337) I find the **PRM class** definition but can not find anywhere to use it. 

Also , in [here](https://github.com/caiyuanhao1998/RSN/blob/master/exps/RSN18.coco/network.py) I can not find **PRM class** definition, either the place to use it. 

So, where the **PRM module** used? Do I foud it in wrong files?

**Comment by caiyuanhao1998** [comment]
You find it in right files. We present an implemention of PRM module. PRM is usually used after the output features of head network before heatmaps. You can try to use it in other places.

**Comment by murdockhou** [comment]
@caiyuanhao1998 Is that means you are not use the PRM module in the release code? Because I can not find anywhere has been used.

**Comment by caiyuanhao1998** [comment]
Yes

**Comment by murdockhou** [comment]
Got it. Thanks.
