### ISSUE TITLE
GPU memory 

### ISSUE THREAD

**Issue by HuangJunJie2017** [caiyuanhao1998/RSN#6]
这个V100塞不下48batch size 的 384x288 4xrsn50吧？8个v100训 384x288 4xrsn50要多久

**Comment by caiyuanhao1998** [comment]
v100开sublinear你能塞下，4×rsn50是用4台8卡机训的，要训5-7天左右，我记得



---Original---

**Comment by HuangJunJie2017** [comment]
sublinear 是FP16？

**Comment by caiyuanhao1998** [comment]
你可以搜一下sublinear，这是一种训练策略，能让gpu吃下更大的model



---Original---
