### ISSUE TITLE
test-dev AP50

### ISSUE THREAD

**Issue by HuangJunJie2017** [caiyuanhao1998/RSN#7]
RSN 在 test-dev上的AP50非常高
我复现RSN18，无论pytorch还是mxnet，AP比论文高不少，但是AP50却还是低一两个点
个人猜测有以下几种可能：
    1）你们的 human det 结果非常好？比HTC强不少，或者针对这个任务有优化
    2）加了额外数据？
    3）有比直接用ohkm更好的策略，平衡训练样本的？

**Comment by caiyuanhao1998** [comment]
我用的human det比htc差，在coco上只有49.4ap。
没有用额外数据
用的就是ohkm



---Original---

**Comment by HuangJunJie2017** [comment]
开源的pytorch 指标低，是框架的问题，还是细节的问题
作者在 pytorch 上能完全复现论文的指标么，还是认为框架会有很大的影响，即使是你也复现不了
如果是框架的差别，觉得是在什么上？Adam不一样？毕竟网络只有卷积，卷积计算也就那样，目前没有发现有换框架后卷积有区别的，那最大问题应该就是Adam或者BN

**Comment by caiyuanhao1998** [comment]
另外megdl采用了cross-bn和sublinear，pytorch没采用。以及pytirch实验超参数没有调整过，直接借用mspn的超参。



---Original---

**Comment by caiyuanhao1998** [comment]
如果花时间调参，我可以在pytorch上复现，不过我为什么要那么做呢?调参只是让baseline增大，不影响delta，这不本质啊。



---Original---

**Comment by caiyuanhao1998** [comment]
我认为框架和细节（code base和一些超参数）都存在差异。我认为应该关注到方法的delta而非绝对值。delta才本质。



---Original---

**Comment by HuangJunJie2017** [comment]
个人觉得这个说法有点问题了，baseline对delta的影响非常大的吧，低baseline啥都work，只有在巅峰baseline上更进一步才是真正的有用吧

**Comment by HuangJunJie2017** [comment]
你写论文也不会拿个低baseline写吧，这样没有说服力

**Comment by caiyuanhao1998** [comment]
这么跟你说吧，megdl的代码，前后调了2个多月参数，调用了超过300张卡。然后pytorch肯定是也能把baseline调上去，要是感兴趣就慢慢去试吧。加油，你这么有毅力，我相信你一定行的。或者你也觉得这种工作太过枯燥乏味，没啥意思还浪费资源的话，可以等megdl代码开源。



---Original---

**Comment by caiyuanhao1998** [comment]
如果你有些问题不方便在这问的话，加我个微信，大家交个朋友聊一聊，搜这个github账号。



---Original---

**Comment by HuangJunJie2017** [comment]
emmm，旷世果然土豪……难怪无论是MSPN还是RSN，都没有能复现的~你这回答具有用，至少我可以跟领导说，你这点卡，我要办到那指标可能性不大，哈哈

**Comment by caiyuanhao1998** [comment]
哈哈，那怪不得你一直在这给我施压。



---Original---

**Comment by caiyuanhao1998** [comment]
以及我已经不在旷视了，这个开源没做好是我能力不行，我的错误，与公司无关。



---Original---

**Comment by caiyuanhao1998** [comment]
mspn的话，头条那边已经复现了，我猜他们也用了蛮多卡的，每年都组织两支队伍参加coco比赛



---Original---

**Comment by HuangJunJie2017** [comment]
我这不算施压吧，我猜是因为你或者旷世没打算放弃这东西能带来的竞争力，所以才会感觉到压力，我问的基本是用这个repo人都想问的问题吧

**Comment by HuangJunJie2017** [comment]
哪里有那么容易，头条去年第三的沿用MSPN 复现的和旷世的差一个点，最后加了一堆东西，还没超过18年MSPN的成绩呢

**Comment by caiyuanhao1998** [comment]
头条78.7，76.3，贵司78.1，76.4。
我觉得他们已经超过了



---Original---

**Comment by HuangJunJie2017** [comment]
那是最后的加了他们自己一些东西之后的指标，复现的结果差一个点，还用了额外数据

**Comment by caiyuanhao1998** [comment]
mspn也用了额外数据，然后头条没有用ensemble。mspn不用ensemble的话只有77.1。



---Original---

**Comment by HuangJunJie2017** [comment]
![image](https://user-images.githubusercontent.com/31001081/79418359-00740d80-7fe7-11ea-9eab-104932031d72.png)
他们报告里面写的

**Comment by HuangJunJie2017** [comment]
你们没有用额外数据是因为训不动么？还是效果不增长了

**Comment by megvii-wzc** [comment]
English Please, Thanks for your attention for our work. More detailed problems about RSN, as well as MSPN, feel free to concat us: wangzhicheng@megvii.com
